apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: galning
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  ingresses:
    - https://galning.nav.no/api/callback
    - https://galning.intern.nav.no/internal/api/authorize
  liveness:
    path: /healthz
    initialDelay: 5
  readiness:
    path: /healthz
    initialDelay: 5
  env:
    - name: BIGQUERY_PROJECT
      value: the-g-team-prod-9be4
    - name: BIGQUERY_DATASET
      value: galning
    - name: BIGQUERY_TABLE
      value: audit_events
    - name: GITHUB_ORG
      value: navikt
    - name: GITHUB_CALLBACK_URL
      value: https://galning.nav.no/api/callback
    - name: GITHUB_TOKEN_SECRET
      value: projects/the-g-team-prod-9be4/secrets/galning-oauth-tokens
  envFrom:
    - secret: galning-ingest
  gcp:
    bigQueryDatasets:
      - name: galning
        permission: READWRITE
    buckets:
      - name: galning
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
